# action.yaml
name: 'Pull Request Metric Action'
description: 'GitHub Action to collect metrics on closing of PR.'
inputs:
  pr_id:
    description: 'Pull-Request Id of PR to analyze.'
    required: true
    default: "1"
  comment_file:
    description: 'Optional path of file with comment.'
    required: false
    default: '${{ github.workspace }}/pr_comment.md'
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Gather and create metrics file
      id: pr-metric
      run: |
        python src/gather_pr_metrics.py ${{ inputs.pr_id }} ${{ inputs.comment_file }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
      shell: bash
