name: Test Action
on:
  pull_request:
    types: [closed]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Returns the number square
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch pull request data
        id: pr-metric
        uses: ./ # Uses an action in the root directory
        # or use a released GitHub Action
        # uses: shipyard/github-action/fetch-shipyard-env@1.0.0
        with:
          # set the PR id to the one that triggered the workflow
          pr_id: ${{ github.event.pull_request.number }}
      - name: Comment on PR
        id: pr-metric
        run: gh pr comment ${{ inputs.pr_id }} --body-file ${{ github.workspace }}/pr_comment.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell: bash
