name: Test Action
on:
  pull_request:
    types: [closed]

jobs:
  add-pr-metric-as-comment:
    runs-on: ubuntu-latest
    name: Returns the number square
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch pull request data
        id: pr-metric
        uses: ./ # Uses an action in the root directory
        with:
          # set the PR id to the one that triggered the workflow
          pr_id: ${{ github.event.pull_request.number }}
      - name: Comment on PR
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body-file ${{ github.workspace }}/pr_comment.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
        # shell: bash
